defaults: &defaults
  name: "Knowledge Base"
  mail:
    smtp:
      address: "smtp.gmail.com"
      port: 587
      domain: "unicorn-world.com"
    account:
      user_name: "notifier@unicorn-world.com"
      password: "do-the-cuca"
  hostname: "localhost:3000"

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
